version: '3'

networks:
    nginx-php8-mysql8-node:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: ngiXB
        ports:
            - "8099:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php8-service
            - mysql8-service
        networks:
            - nginx-php8-mysql8-node

    # php
    php8-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: phpXB
        ports:
            - "9090:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php8-mysql8-node

    # mysql
    mysql8-service:
        image: mariadb:10.4
        container_name: mysqlXB
        ports:
            - "4396:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: mysqld --sql_mode="" --default-time-zone='+01:00'
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_ROOT_USER: root
            MYSQL_USER: root
            MYSQL_PASSWORD: secret


        networks:
            - nginx-php8-mysql8-node

    # node
    node-service:
        image: node:latest
        container_name: nodeXB
        volumes:
            - ./app:/var/www/project
        working_dir: /var/www/project
        networks:
            - nginx-php8-mysql8-node